allowBuilds:
  esbuild: false
overrides:
  vite@*: npm:@voidzero-dev/vite-plus-core@1.0.0
  vitest@*: 5.0.1
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
